# Generated by Django 5.2.1 on 2025-05-26 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_length', models.PositiveIntegerField(default=0)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_description_length', models.PositiveIntegerField(default=0)),
                ('h1_count', models.PositiveIntegerField(default=0)),
                ('h2_count', models.PositiveIntegerField(default=0)),
                ('h3_count', models.PositiveIntegerField(default=0)),
                ('h1_text', models.TextField(blank=True, null=True)),
                ('h2_texts', models.JSONField(default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword_count', models.PositiveIntegerField(default=0)),
                ('keyword_density', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('recommended_keyword_count', models.PositiveIntegerField(default=0)),
                ('paragraphs', models.JSONField(default=list)),
                ('images_count', models.PositiveIntegerField(default=0)),
                ('missing_alt_images_count', models.PositiveIntegerField(default=0)),
                ('has_canonical', models.BooleanField(default=False)),
                ('has_schema_markup', models.BooleanField(default=False)),
                ('schema_types', models.JSONField(default=list)),
                ('internal_links_count', models.PositiveIntegerField(default=0)),
                ('external_links_count', models.PositiveIntegerField(default=0)),
                ('largest_contentful_paint', models.FloatField(null=True, verbose_name='LCP (ms)')),
                ('first_input_delay', models.FloatField(null=True, verbose_name='FID (ms)')),
                ('cumulative_layout_shift', models.FloatField(null=True, verbose_name='CLS')),
                ('mobile_friendly', models.BooleanField(default=False)),
                ('https', models.BooleanField(default=False)),
                ('content_readability_score', models.FloatField(null=True)),
                ('duplicate_content', models.BooleanField(default=False)),
                ('thin_content', models.BooleanField(default=False)),
                ('content_freshness', models.DateField(null=True)),
                ('semantic_keywords', models.JSONField(default=list)),
                ('robots_txt_status', models.BooleanField(default=False)),
                ('sitemap_status', models.BooleanField(default=False)),
                ('page_load_time', models.FloatField(null=True)),
                ('render_blocking_resources', models.JSONField(default=list)),
                ('lazy_loading_images', models.BooleanField(default=False)),
                ('schema_errors', models.JSONField(default=list)),
                ('rich_snippet_opportunities', models.JSONField(default=list)),
                ('faq_schema_present', models.BooleanField(default=False)),
                ('breadcrumb_schema_present', models.BooleanField(default=False)),
                ('author_credentials', models.BooleanField(default=False)),
                ('author_bylines', models.BooleanField(default=False)),
                ('citation_sources', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(null=True)),
                ('contact_info_present', models.BooleanField(default=False)),
                ('seo_health_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hreflang_implemented', models.BooleanField(default=False)),
                ('image_compression_score', models.FloatField(null=True)),
                ('security_headers', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
